### PR TITLE
74 create tags component

### PR DESCRIPTION
**Pull request by samanthatuhseng**
pls review

### CODE REVIEW

**Comment by DonaldKLee** [comment]
npm run storybook causes this error. Seems like it's missing TagCSS
image

@samanthatuhseng @ajo01 should we update this branch? 
image

**Comment by samanthatuhseng** [comment]
oh shoot, yea my bad I deleted the file and forgot to take it off the code as well lemme quickly fix it

**Comment by ajo01** [comment]
@samanthatuhseng just curious, why didn't you make the border color, background, and text colors as props? wouldn't that have been simpler to implement rather than having 3 props that have precedence over each other?

**Comment by samanthatuhseng** [comment]
I think it was cause I already started implementing it that way and wanted to follow the figma. So, I thought this might have been more "accurate." But I can change that if you prefer it the other way?

**Comment by ajo01** [comment]
you could either pass color props as I initially suggested or you could keep your active, selectable, and selected props but make it into a single prop. for the latter, this is advisable since the styles you're applying are exclusive from one another. so you could have a single prop called type, which can have values such as active, selectable, and selected and you can apply your styles based on the value of this prop

like this

`const Tags = ({type})`  // line 5 of tags.js

```
if (type === 'active') {
// add styles here
} else if (type === 'selected') {
// add styles here
} else {
// add styles here
}
```

**Comment by samanthatuhseng** [comment]
gotcha will do!

**Pull request closed without merging**
